// DracView.c ... DracView ADT implementation

#include <stdlib.h>
#include <assert.h>
#include "Globals.h"
#include "Game.h"
#include "GameView.h"
#include "DracView.h"
// #include "Map.h" ... if you decide to use the Map ADT


typedef struct _encounters {
    LocationID location;
    char type;
} encounters;

struct dracView {
    GameView gV;              // generated by newGameView()
    encounters eTrail[TRAIL_SIZE];  // trail of active encounters (T/V)
};


// Creates a new DracView to summarise the current state of the game
DracView newDracView(char *pastPlays, PlayerMessage messages[]) {

    DracView dracView = malloc(sizeof(struct dracView));
    dracView->gV = newGameView(pastPlays, messages);

    // now to start making eTrail[]...
    char *playTracker;
    int j;

    // make it empty first...
    for (j = 0; j < TRAIL_SIZE - 1; j++) {
        dracView->eTrail[j].location = NOWHERE;
        dracView->eTrail[j].type = '.';
    }

    // now to update it to the game state...
    for (playTracker = pastPlays;
         playTracker != pastPlays + 8 * gameView->turnNum; //////////////////////////////////////////////
         pastPlays += 8) {
        PlayerID p = 0;
        switch (playTracker[0]) {
            case 'G': p = PLAYER_LORD_GODALMING; break;
            case 'S': p = PLAYER_DR_SEWARD; break;
            case 'H': p = PLAYER_VAN_HELSING; break;
            case 'M': p = PLAYER_MINA_HARKER; break;
            case 'D': p = PLAYER_DRACULA; break;
        }

        if (p == PLAYER_DRACULA) { // it's dracula!
            if (playTracker[3] == 'T') {
                // adjust eTrail[]...
                // oldest at the front, newest at the end...

                // shift the array...
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    dracView->eTrail[j].location =
                        dracView->eTrail[j+1].location;
                    dracView->eTrail[j].type =
                        dracView->eTrail[j+1].type;
                }

                // add the new encounter...
                dracView->eTrail[TRAIL_SIZE - 1].location =
                    abbrevToID(playTracker[1]);
                dracView->eTrail[TRAIL_SIZE - 1].type = 'T';

            } else if (playTracker[4] == 'V') {
                // adjust eTrail[]...
                // newest at the front, oldest at the end...

                // shift the array...
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    dracView->eTrail[j].location =
                        dracView->eTrail[j+1].location;
                    dracView->eTrail[j].type =
                        dracView->eTrail[j+1].type;
                }

                // add the new encounter...
                dracView->eTrail[TRAIL_SIZE - 1].location =
                    abbrevToID(playTracker[1]);
                dracView->eTrail[TRAIL_SIZE - 1].type = 'V';

            }

        } else { // it's a hunter!
            // immature vampires...
            if (playTracker[3] == 'V') {
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    if (dracView->eTrail[j].location ==
                        abbrevToID(playTracker[1]) &&
                        dracView->eTrail[j].type == 'T') {
                        break;
                    }
                }
                dracView->eTrail[j].location == NOWHERE;
                dracView->eTrail[j].type == '.';
    	    }

            // traps...
            if (playTracker[3] == 'T') {
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    if (dracView->eTrail[j].location ==
                        abbrevToID(playTracker[1]) &&
                        dracView->eTrail[j].type == 'T') {
                        break;
                    }
                }
                dracView->eTrail[j].location == NOWHERE;
                dracView->eTrail[j].type == '.';
            }
    	    if (playTracker[4] == 'T') {
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    if (dracView->eTrail[j].location ==
                        abbrevToID(playTracker[1]) &&
                        dracView->eTrail[j].type == 'T') {
                        break;
                    }
                }
                dracView->eTrail[j].location == NOWHERE;
                dracView->eTrail[j].type == '.';
            }
            if (playTracker[5] == 'T') {
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    if (dracView->eTrail[j].location ==
                        abbrevToID(playTracker[1]) &&
                        dracView->eTrail[j].type == 'T') {
                        break;
                    }
                }
                dracView->eTrail[j].location == NOWHERE;
                dracView->eTrail[j].type == '.';
    	    }
            if (playTracker[6] == 'T') {
                for (j = 0; j < TRAIL_SIZE - 1; j++) {
                    if (dracView->eTrail[j].location ==
                        abbrevToID(playTracker[1]) &&
                        dracView->eTrail[j].type == 'T') {
                        break;
                    }
                }
                dracView->eTrail[j].location == NOWHERE;
                dracView->eTrail[j].type == '.';
    	    }
        }
    }

    return dracView;
}


// Frees all memory previously allocated for the DracView toBeDeleted
void disposeDracView(DracView toBeDeleted) {
    assert(toBeDeleted != NULL);
    assert(toBeDeleted->gV != NULL);
    disposeGameView(toBeDeleted->game);
    free(toBeDeleted);
}


//// Functions to return simple information about the current state of the game

// Get the current round
Round giveMeTheRound(DracView currentView) {
    return getRound(currentView->gV);
}

// Get the current score
int giveMeTheScore(DracView currentView) {
    return getScore(currentView->gV);
}

// Get the current health points for a given player
int howHealthyIs(DracView currentView, PlayerID player) {
    return getHealth(currentView->gV, player);
}

// Get the current location id of a given player
LocationID whereIs(DracView currentView, PlayerID player) {
    return getLocation(currentView->gV, player);
}

// Get the most recent move of a given player
void lastMove(DracView currentView, PlayerID player,
                 LocationID *start, LocationID *end) {
    LocationID trail[TRAIL_SIZE];
    getHistory(currentView->gV, player, trail);
    *start = trail[TRAIL_SIZE-2];
    *end = trail[TRAIL_SIZE-1];
    return;
}

// Find out what minions are placed at the specified location
void whatsThere(DracView currentView, LocationID where,
                         int *numTraps, int *numVamps) {
    int j;
    for (j = 0; j < TRAIL_SIZE - 1; j++) {
        if (dracView->eTrail[j].location == where) {
            if (dracView->eTrail[j].type == 'T') {
                *numTraps++;
            } else if (dracView->eTrail[j].type == 'V') {
                *numVamps++;
            }
        }
    }
    return;
}

//// Functions that return information about the history of the game

// Fills the trail array with the location ids of the last 6 turns
void giveMeTheTrail(DracView currentView, PlayerID player,
                            LocationID trail[TRAIL_SIZE]) {
    getHistory(currentView->gV,player, trail);
    return;
}

//// Functions that query the map to find information about connectivity

// What are my (Dracula's) possible next moves (locations)
LocationID *whereCanIgo(DracView currentView, int *numLocations, int road, int sea) {
    LocationID trail[TRAIL_SIZE];
    getHistory(currentView->gV, player, trail);
    LocationID * connections =
        connectedLocations(currentView->gV, numLocations,
                           getLocation(currentView->gV,PLAYER_DRACULA),
                           PLAYER_DRACULA, getRound(currentView->gV),
                           road, FALSE, sea);
    int i;
    int j;
    for (j = 0; j < TRAIL_SIZE - 1; j++) {
        for (i = 0; connectedLocations[i] != '\0'; i++) {
            if (trail[j] == connectedLocations[i]) {
                connectedLocations[i] = NOWHERE;
            }
        }
    }
    return connections;
}

// What are the specified player's next possible moves
LocationID *whereCanTheyGo(DracView currentView, int *numLocations,
                           PlayerID player, int road, int rail, int sea) {
    if (player == PLAYER_DRACULA) {
        return whereCanIgo(currentView, numLocations,road,FALSE,sea);
    }
    return connectedLocations(currentView->gV, numLocations,
                              getLocation(currentView->gV,player),
                              player, getRound(currentView->gV),
                              road, rail, sea);
}
