// HunterView.c ... HunterView ADT implementation

#include <stdlib.h>
#include <assert.h>
#include "Globals.h"
#include "Game.h"
#include "GameView.h"
#include "HunterView.h"
// #include "Map.h" ... if you decide to use the Map ADT

struct hunterView {
<<<<<<< HEAD
    GameView gV;                    // generated by newGameView()
    PlayerID player;                // ID of the player
=======
    int score;
    int health[NUM_PLAYERS];
    Round round;
    LocationID location[NUM_PLAYERS][TRAIL_SIZE];
>>>>>>> a56425b3bcc0400bbb4e9ccbd5d62cd36e223462
};


// Creates a new HunterView to summarise the current state of the game
HunterView newHunterView(char *pastPlays, PlayerMessage messages[]) {
    HunterView hunterView = malloc(sizeof(struct hunterView));
    hunterView->gV = newGameView(pastPlays, messages);
    hunterView->player = getCurrentPlayer(hunterView->gV);
    return hunterView;
}


// Frees all memory previously allocated for the HunterView toBeDeleted
<<<<<<< HEAD
void disposeHunterView(HunterView toBeDeleted) {
    assert(toBeDeleted != NULL);
    assert(toBeDeleted->gV != NULL);
    disposeGameView(toBeDeleted->gV);
    free(toBeDeleted);
=======
void disposeHunterView(HunterView toBeDeleted)
{
    if(toBeDeleted == 0){
        printf("Nothing to delete.");
        return 0;
    } else {
        free(toBeDeleted);
    }
>>>>>>> a56425b3bcc0400bbb4e9ccbd5d62cd36e223462
}


//// Functions to return simple information about the current state of the game

// Get the current round
<<<<<<< HEAD
Round giveMeTheRound(HunterView currentView) {
    return getRound(currentView->gV);
=======
Round giveMeTheRound(HunterView currentView)
{
    return currentView->round;
>>>>>>> a56425b3bcc0400bbb4e9ccbd5d62cd36e223462
}

// Get the id of current player
PlayerID whoAmI(HunterView currentView) {
    return currentView->player;
}

// Get the current score
<<<<<<< HEAD
int giveMeTheScore(HunterView currentView) {
    return getScore(currentView->gV);
}

// Get the current health points for a given player
int howHealthyIs(HunterView currentView, PlayerID player) {
    assert(player >= PLAYER_LORD_GODALMING && player <= PLAYER_DRACULA);
    return getHealth(currentView->gV, player);
}

// Get the current location id of a given player
LocationID whereIs(HunterView currentView, PlayerID player) {
    assert(player >= PLAYER_LORD_GODALMING && player <= PLAYER_DRACULA);
    return getLocation(currentView->gV, player);
=======
int giveMeTheScore(HunterView currentView)
{
    return currentView->score;
}

// Get the current health points for a given player
int howHealthyIs(HunterView currentView, PlayerID player)
{
    return currentView->health[player];
}

// Get the current location id of a given player
LocationID whereIs(HunterView currentView, PlayerID player)
{
    if(round == 0){
        return UKNOWN_LOCATION;
    } else {
        return currentView->location[player][0];
    }
>>>>>>> a56425b3bcc0400bbb4e9ccbd5d62cd36e223462
}

//// Functions that return information about the history of the game

// Fills the trail array with the location ids of the last 6 turns
void giveMeTheTrail(HunterView currentView, PlayerID player,
                            LocationID trail[TRAIL_SIZE]) {
    return getHistory(currentView->gV, player, trail);
}

//// Functions that query the map to find information about connectivity

// What are my possible next moves (locations)
LocationID *whereCanIgo(HunterView currentView, int *numLocations,
                        int road, int rail, int sea) {
    return connectedLocations(currentView->gV, numLocations,
                              getLocation(currentView->gV,currentView->player),
                              currentView->player, getRound(currentView->gV),
                              road, rail, sea);
}

// What are the specified player's next possible moves
LocationID *whereCanTheyGo(HunterView currentView, int *numLocations,
                           PlayerID player, int road, int rail, int sea) {
    if (player == PLAYER_DRACULA                             &&
        (getLocation(currentView->gV, player) < ADRIATIC_SEA &&
         getLocation(currentView->gV, player) > ZURICH)        ) {
        return connectedLocations(currentView->gV, numLocations,
                                  getLocation(currentView->gV,currentView->player),
                                  currentView->player, getRound(currentView->gV),
                                  FALSE, FALSE, FALSE);
    }
    return connectedLocations(currentView->gV, numLocations,
                              getLocation(currentView->gV,currentView->player),
                              currentView->player, getRound(currentView->gV),
                              road, rail, sea);
}
